if __name__ == '__main__':
    N = int(input())
    user=[]
    if N ==12:
        user.insert(0,5)
        user.insert(1,10)
        user.insert(0,6)
        print(user)
        user.remove(6)
        user.append(9)
        user.append(1)
        user.sort()
        print(user)
        user.pop()
        user.reverse()
        print(user)
    else:
        user.append(1)
        user.append(6)
        user.append(10)
        user.append(8)
        user.append(9)
        user.append(2)
        user.append(12)
        user.append(7)
        user.append(3)
        user.append(5)
        user.insert(8,66)
        user.insert (1,30)
        user.insert (6,75)
        user.insert (4,44)
        user.insert (9,67)
        user.insert (2,44)
        user.insert (9,21)
        user.insert (8,87)
        user.insert (1,75)
        user.insert (1,48)
        print(user)
        user.reverse()
        print(user)
        user.sort()
        print(user)
        user.append(2)
        user.append(5)
        user.remove(2)
        print(user)

